<?php
declare(strict_types=1);

namespace WebMeridian\JsLayoutExample\Block\Example;

use Magento\Framework\View\Element\Template;

class OnePage extends \Magento\Framework\View\Element\Template
{


    /**
     * @return string
     */
    public function getJsLayout()
    {
        return parent::getJsLayout(); // TODO: Change the autogenerated stub
    }

}

